services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
        - app-network

networks:
    app-network: