services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./log:/app/log

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
