apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: CALLBACK_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  key: CALLBACK_REDIRECT_URI
                  name: env
            - name: DISCORD_BOT_TOKEN_1
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_BOT_TOKEN_1
                  name: env
            - name: DISCORD_BOT_TOKEN_2
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_BOT_TOKEN_2
                  name: env
            - name: DISCORD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_ID
                  name: env
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_SECRET
                  name: env
            - name: DISCORD_ENV
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ENV
                  name: env
            - name: DISCORD_GUILD_ID
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_GUILD_ID
                  name: env
            - name: DISCORD_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_REDIRECT_URI
                  name: env
            - name: DISCORD_SERVER_INVITE
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_SERVER_INVITE
                  name: env
            - name: HENRIK_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: HENRIK_API_TOKEN
                  name: env
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: env
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PASSWORD
                  name: env
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_USERNAME
                  name: env
            - name: NEATQUEUE_API
              valueFrom:
                configMapKeyRef:
                  key: NEATQUEUE_API
                  name: env
            - name: SERVER_IP
              valueFrom:
                configMapKeyRef:
                  key: SERVER_IP
                  name: env
            - name: SESSION_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SESSION_SECRET_KEY
                  name: env
            - name: VALORANTSL_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VALORANTSL_API_URL
                  name: env
          image: naheedroomy/valorantsl-frontend:1.3
          name: streamlit
          ports:
            - containerPort: 8501
              protocol: TCP
      restartPolicy: Always
