name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PEM_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@15.206.154.147 << 'EOF'
          sudo bash -c '
            cd /root/valorantsl
            git pull origin main
            docker compose down
            docker compose up --build -d
            docker images -a | grep none | awk '{ print $3; }' | xargs docker rmi
          '
        EOF
